
server:
  port: 8087

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dilect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  rabbitmq:
    port: 5672
    host: localhost
    exchange:
        name: exchangeTest1
        key: testKey1

