server:
  port: 8088

spring:
  rabbitmq:
    port: 5672
    host: localhost
    exchange:
      receiver:
         name: exchangeTest1
         key: testKey1
         queue: queueTest1
      sender:
        name: exchangeTest2
        key: testKey2

